[package]
name = "ros2msg_example"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
oxidros = { path = "../../oxidros/" }

[build-dependencies]
ros2-msg-gen = { path = "../../ros2-msg-gen/" }
