[workspace]
members = [
    "oxidros",
    "oxidros-core",
    "oxidros-msg",
    "oxidros-wrapper",
    "ros2-msg-gen",
    "examples/ros2msg_example",
]
resolver = "2"

[workspace.package]
edition = "2021"
authors = ["Nadhmi JAZI <nadhmi.eljazi@gmail.com>"]
repository = "https://github.com/jazi007/oxidros"
license-file = "LICENSE"

[workspace.dependencies]
num-traits = "0.2"
futures = "0.3"
