[package]
name = "oxidros-wrapper"
version = "0.1.7"
description = "A wrapper around oxidros"
license-file.workspace = true
edition.workspace = true
authors.workspace = true
repository.workspace = true


[dependencies]
futures = "0.3"
log = { version = "0.4", features = ["std"] }
oxidros = { path = "../oxidros" }
tokio-stream = "0.1"
tokio-util = "0.7"
tokio = { version = "1", features = ["time"] }
yaml-rust2 = "0.11"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

