[package]
name = "oxidros"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
oxidros-core = { path = "../oxidros-core" }
oxidros-msg = { path = "../oxidros-msg" }
oxidros-rcl = { path = "../oxidros-rcl" }
oxidros-zenoh = { path = "../oxidros-zenoh"}

[dev-dependencies]
tokio = { version = "1", features = ["full"] }

[build-dependencies]
oxidros-build = { path = "../oxidros-build" }

[features]
default = []
rcl = ["oxidros-msg/rcl"]
zenoh = []

# RCL distribution features (require rcl feature)
humble = ["rcl", "oxidros-rcl/humble", "oxidros-msg/humble"]
jazzy = ["rcl", "oxidros-rcl/jazzy", "oxidros-msg/jazzy"]
kilted = ["rcl", "oxidros-rcl/kilted", "oxidros-msg/kilted"]
