[package]
name = "oxidros"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
repository.workspace = true
license-file.workspace = true

[dependencies]
oxidros-rcl = { path = "../oxidros-rcl" }

[build-dependencies]
oxidros-build = { path = "../oxidros-build" }

[features]
default = []
humble = ["oxidros-rcl/humble"]
jazzy = ["oxidros-rcl/jazzy"]
kilted = ["oxidros-rcl/kilted"]
