[package]
name = "oxidros"
version = "0.4.6"
description = "Oxidros: Formally Specified Rust Bindings for ROS2"
license-file = "LICENSE"
readme = "README.md"
keywords = ["Robotics", "ROS2"]
categories = ["science::robotics"]
repository.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
oxidros-core = { path = "../oxidros-core" }
oxidros-msg = { path = "../oxidros-msg" }
oxidros-rcl = { path = "../oxidros-rcl" }
crossbeam-channel = "0.5"
futures.workspace = true
libc = "0.2"
num-derive = "0.4"
num-traits.workspace = true
once_cell = "1.14"
parking_lot = "0.12"
pin-project = "1.0"
regex = "1.10"
serde = { version = "1", features = ["derive"], optional = true }
serde_json = { version = "1", optional = true }
signal-hook = "0.3"

[dev-dependencies]
tokio = { version = "1", features = ["full"] }
futures.workspace = true
memac = "0.5"
rand = "0.9"

[build-dependencies]
oxidros-build = { path = "../oxidros-build" }

[features]
default = []
custom_alloc = []
humble = ["oxidros-msg/humble"]
jazzy = ["oxidros-msg/jazzy"]
kilted = ["oxidros-msg/kilted"]
rcl_stat = ["statistics"]
statistics = ["serde", "serde_json"]

[package.metadata.docs.rs]
features = ["jazzy", "custom_alloc"]
all-features = false
no-default-features = true
