[package]
name = "oxidros"
version = "0.4.6"
description = "Oxidros: Formally Specified Rust Bindings for ROS2"
license-file = "LICENSE"
readme = "README.md"
keywords = ["Robotics", "ROS2"]
categories = ["science::robotics"]
repository.workspace = true
edition.workspace = true
authors.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oxidros-core = { path = "../oxidros-core" }
oxidros-msg = { path = "../oxidros-msg" }
oxidros-rcl = { path = "../oxidros-rcl" }
num-traits.workspace = true
num-derive = "0.4"
once_cell = "1.14"
crossbeam-channel = "0.5"
parking_lot = "0.12"
signal-hook = "0.3"
libc = "0.2"
pin-project = "1.0"
regex = "1.10.4"
futures.workspace = true

[dependencies.serde]
version = "1"
features = ["derive"]
optional = true

[dependencies.serde_json]
version = "1"
optional = true

[dev-dependencies.memac]
version = "0.5"

[dev-dependencies]
futures.workspace = true
rand = "0.9"

[dev-dependencies.async-std]
version = "1.12"
features = ["attributes"]

[features]
default = []
statistics = ["serde", "serde_json"]
rcl_stat = ["statistics"]
jazzy = ["oxidros-msg/jazzy"]
iron = ["oxidros-msg/iron"]
humble = ["oxidros-msg/humble"]
galactic = ["oxidros-msg/galactic"]
custom_alloc = []

[package.metadata.docs.rs]

# Features to pass to Cargo (default: [])
features = ["jazzy", "custom_alloc"]

# Whether to pass `--all-features` to Cargo (default: false)
all-features = false

# Whether to pass `--no-default-features` to Cargo (default: false)
no-default-features = true

[build-dependencies]
oxidros-build = { path = "../oxidros-build" }
